version: '3.8'
services:
  cypress_compose:
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./dockerReports:/app/allure-report
    stdin_open: true
    tty: true
    command: npm run cucumber:tags
