# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: celiscorp
# "service" is the name of this project. This will also be added to your AWS resource names.
service: crud-serverless-course

frameworkVersion: "4"

provider:
  name: aws
  runtime: nodejs20.x
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - 'dynamodb:PutItem'
            - 'dynamodb:GetItem'
            - 'dynamodb:Query'
            - 'dynamodb:UpdateItem'
            - 'dynamodb:DeleteItem'
          Resource: arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-customerTable-${sls:stage}
  environment:
    DYNAMODB_CUSTOMER_TABLE: ${self:service}-customerTable-${sls:stage}

plugins:
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true
  patterns:
    - "!node_modules/**"
    - "!.dynamodb/**"
    - "!.serverless/**"


custom:
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    # Uncomment only if you already have a DynamoDB running locally
    # noStart: true

functions:
  hello-world:
    handler: hello-world/handler.hello
    events:
      - httpApi:
          path: /hello
          method: GET

  get-users:
    handler: getUsers/handler.getUsers
    events:
      - httpApi:
          path: /users/{id}
          method: GET
  
  create-users:
    handler: createUsers/handler.createUsers
    events:
      - httpApi:
          path: /users
          method: POST

  update-users:
    handler: updateUsers/handler.updateUsers
    events:
      - httpApi:
          path: /users/{id}
          method: PATCH

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        BillingMode: PAY_PER_REQUEST
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        TableName: ${self:service}-customerTable-${sls:stage}
