# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: celiscorp
service: poemas-geek

provider:
  name: aws
  runtime: python3.10
  region: us-east-1
  environment:
    OPENAIKEY: ${ssm:/openaikey, "fake-openaikey"}
    OPENAIORG: ${ssm:/openaiorg, "fake-openaiorg"}

functions:
  generar-poema:
    handler: handler.generarPoema
    events:
      - http:
          path: generar-poema
          method: post
          request:
            schemas:
              application/json: ${file(./schema_poema.json)}
