/*CREATE TABLE COURSES (
	COURSEID INT PRIMARY KEY AUTOINCREMENT,
  	COURSENAME VARCHAR(100),
  	DESCRIPTION TEXT,
  	INSTRUCTORID INT,
  	DURATIONHOURS INT,
  	LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	FOREIGN KEY (INSTRUCTORID) REFERENCES INSTRUCTORS(INSTRUCTORID) 
);*/

-- Creación de la tabla COURSES
CREATE TABLE COURSES (
    COURSEID INTEGER PRIMARY KEY AUTOINCREMENT,  -- Clave primaria con autoincremento
    COURSENAME VARCHAR(100) NOT NULL,            -- Nombre del curso
    DESCRIPTION TEXT,                            -- Descripción opcional
    INSTRUCTORID INT,                            -- Relación con un instructor
    DURATIONHOURS INT,                           -- Duración en horas
    LOAD_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,   -- Fecha de creación
    UPDATE_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP, -- Fecha de actualización
    FOREIGN KEY (INSTRUCTORID) REFERENCES INSTRUCTOR(Instructor) -- Relación con tabla INSTRUCTOR
);
