CREATE TABLE STUDENT_COURSE (
    STUDENT_COURSE_ID INTEGER PRIMARY KEY,
    STUDENTID INTEGER,
    COURSEID INTEGER,
    ENROLLMENT_DATE TIMESTAMP,
    LOAD_DATE TIMESTAMP,
    UPDATE_DATE TIMESTAMP
);
