--- 23-08-2025 18:32:16 SQLite.7
CREATE table INSTRUCTORS1 (
	INSTRUCTORID INT PRIMARY KEY,
  	FIRSTNAME VARCHAR(50),
  	LASTNAME VARCHAR(50),
  	EMAIL VARCHAR(50),
  	LOADDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  	UPDATEDATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);


