version: '3'
services:
  web-server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:  # Para que se actualice automáticamente.
      - .:/app 
    ports:
      - '80:80'