insert into estaciones (id_estacion, nombre, direccion) values (1, 'Fordem', '621 Green Drive');
insert into estaciones (id_estacion, nombre, direccion) values (2, 'Mcbride', '21303 Towne Junction');
insert into estaciones (id_estacion, nombre, direccion) values (3, 'Milwaukee', '885 Vidon Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (4, 'Stephen', '749 Eagan Alley');
insert into estaciones (id_estacion, nombre, direccion) values (5, 'Bay', '36262 Charing Cross Way');
insert into estaciones (id_estacion, nombre, direccion) values (6, 'Carioca', '19 Summit Circle');
insert into estaciones (id_estacion, nombre, direccion) values (7, 'Amoth', '44 Clove Trail');
insert into estaciones (id_estacion, nombre, direccion) values (8, 'Tomscot', '91 Westport Center');
insert into estaciones (id_estacion, nombre, direccion) values (9, 'Gina', '59246 West Court');
insert into estaciones (id_estacion, nombre, direccion) values (10, 'Schiller', '59 Fallview Court');
insert into estaciones (id_estacion, nombre, direccion) values (11, 'Thompson', '4 Corry Trail');
insert into estaciones (id_estacion, nombre, direccion) values (12, 'Blackbird', '33065 Melody Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (13, 'Melby', '6121 Ridgeview Circle');
insert into estaciones (id_estacion, nombre, direccion) values (14, 'Dorton', '4 Mendota Alley');
insert into estaciones (id_estacion, nombre, direccion) values (15, 'Springview', '0 Waxwing Lane');
insert into estaciones (id_estacion, nombre, direccion) values (16, 'Sundown', '37 Spenser Park');
insert into estaciones (id_estacion, nombre, direccion) values (17, 'Delaware', '642 Northwestern Plaza');
insert into estaciones (id_estacion, nombre, direccion) values (18, 'Crescent Oaks', '47124 Sullivan Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (19, 'Ridgeview', '7322 Sloan Pass');
insert into estaciones (id_estacion, nombre, direccion) values (20, 'Sunnyside', '92352 Sullivan Junction');
insert into estaciones (id_estacion, nombre, direccion) values (21, 'North', '251 Rieder Pass');
insert into estaciones (id_estacion, nombre, direccion) values (22, 'Service', '124 Pond Place');
insert into estaciones (id_estacion, nombre, direccion) values (23, 'Esker', '10964 Vidon Street');
insert into estaciones (id_estacion, nombre, direccion) values (24, 'Kinsman', '716 Charing Cross Lane');
insert into estaciones (id_estacion, nombre, direccion) values (25, 'Green', '4762 Ridgeway Circle');
insert into estaciones (id_estacion, nombre, direccion) values (26, 'Dennis', '5 Annamark Hill');
insert into estaciones (id_estacion, nombre, direccion) values (27, 'Trailsway', '924 Emmet Circle');
insert into estaciones (id_estacion, nombre, direccion) values (28, 'Prairieview', '95 Cottonwood Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (29, 'Northwestern', '507 Di Loreto Circle');
insert into estaciones (id_estacion, nombre, direccion) values (30, 'Golden Leaf', '40 Dwight Lane');
insert into estaciones (id_estacion, nombre, direccion) values (31, 'Basil', '68 Roxbury Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (32, 'Fairview', '02530 Bluejay Point');
insert into estaciones (id_estacion, nombre, direccion) values (33, 'Delladonna', '26377 Menomonie Court');
insert into estaciones (id_estacion, nombre, direccion) values (34, 'Boyd', '72511 Sugar Trail');
insert into estaciones (id_estacion, nombre, direccion) values (35, 'Hollow Ridge', '5445 Meadow Valley Center');
insert into estaciones (id_estacion, nombre, direccion) values (36, 'Bartillon', '97 Thackeray Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (37, 'Gateway', '48556 Myrtle Trail');
insert into estaciones (id_estacion, nombre, direccion) values (38, 'Hagan', '79 Crescent Oaks Lane');
insert into estaciones (id_estacion, nombre, direccion) values (39, 'Sachs', '9529 Hauk Pass');
insert into estaciones (id_estacion, nombre, direccion) values (40, 'Del Sol', '36 Goodland Circle');
insert into estaciones (id_estacion, nombre, direccion) values (41, 'Prentice', '24861 Ridgeway Trail');
insert into estaciones (id_estacion, nombre, direccion) values (42, 'Nevada', '8 Gulseth Park');
insert into estaciones (id_estacion, nombre, direccion) values (43, 'Birchwood', '1311 Cascade Park');
insert into estaciones (id_estacion, nombre, direccion) values (44, 'Randy', '33 Waubesa Lane');
insert into estaciones (id_estacion, nombre, direccion) values (45, 'Anhalt', '1225 Merrick Place');
insert into estaciones (id_estacion, nombre, direccion) values (46, 'Norway Maple', '4 Mallory Hill');
insert into estaciones (id_estacion, nombre, direccion) values (47, 'Corry', '08 Del Mar Parkway');
insert into estaciones (id_estacion, nombre, direccion) values (48, 'Redwing', '0625 Mallard Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (49, 'Twin Pines', '60 Anderson Hill');
insert into estaciones (id_estacion, nombre, direccion) values (50, 'Fordem', '31 Emmet Pass');
insert into estaciones (id_estacion, nombre, direccion) values (51, 'Blaine', '28904 Bashford Road');
insert into estaciones (id_estacion, nombre, direccion) values (52, 'Golf Course', '85 Carioca Parkway');
insert into estaciones (id_estacion, nombre, direccion) values (53, 'Hallows', '9948 Russell Alley');
insert into estaciones (id_estacion, nombre, direccion) values (54, 'Gina', '7074 Esch Pass');
insert into estaciones (id_estacion, nombre, direccion) values (55, 'Atwood', '87 Mcguire Center');
insert into estaciones (id_estacion, nombre, direccion) values (56, 'Arapahoe', '574 Huxley Parkway');
insert into estaciones (id_estacion, nombre, direccion) values (57, 'East', '9 Becker Circle');
insert into estaciones (id_estacion, nombre, direccion) values (58, 'Hallows', '4 Maywood Court');
insert into estaciones (id_estacion, nombre, direccion) values (59, 'Knutson', '5637 Sommers Way');
insert into estaciones (id_estacion, nombre, direccion) values (60, 'Fieldstone', '71 Homewood Way');
insert into estaciones (id_estacion, nombre, direccion) values (61, 'Tennessee', '2 Summerview Trail');
insert into estaciones (id_estacion, nombre, direccion) values (62, 'Twin Pines', '2 Fremont Drive');
insert into estaciones (id_estacion, nombre, direccion) values (63, 'Jenna', '73 Carioca Pass');
insert into estaciones (id_estacion, nombre, direccion) values (64, 'Moulton', '4 Lien Parkway');
insert into estaciones (id_estacion, nombre, direccion) values (65, 'Butterfield', '8 Fieldstone Point');
insert into estaciones (id_estacion, nombre, direccion) values (66, 'Lunder', '3 Luster Pass');
insert into estaciones (id_estacion, nombre, direccion) values (67, 'Emmet', '991 Trailsway Trail');
insert into estaciones (id_estacion, nombre, direccion) values (68, 'Victoria', '159 Dennis Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (69, 'Del Sol', '57 Waxwing Circle');
insert into estaciones (id_estacion, nombre, direccion) values (70, 'Lindbergh', '428 Miller Road');
insert into estaciones (id_estacion, nombre, direccion) values (71, 'Pankratz', '6 Gina Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (72, 'Straubel', '7 Katie Drive');
insert into estaciones (id_estacion, nombre, direccion) values (73, 'Mayer', '2 Cody Plaza');
insert into estaciones (id_estacion, nombre, direccion) values (74, 'Oneill', '606 Derek Point');
insert into estaciones (id_estacion, nombre, direccion) values (75, 'Darwin', '76 Vermont Park');
insert into estaciones (id_estacion, nombre, direccion) values (76, 'Gale', '20005 2nd Center');
insert into estaciones (id_estacion, nombre, direccion) values (77, 'Knutson', '9 Maple Wood Trail');
insert into estaciones (id_estacion, nombre, direccion) values (78, 'Annamark', '8 Center Park');
insert into estaciones (id_estacion, nombre, direccion) values (79, 'Schiller', '93 Calypso Road');
insert into estaciones (id_estacion, nombre, direccion) values (80, 'Rusk', '97660 Kings Parkway');
insert into estaciones (id_estacion, nombre, direccion) values (81, 'Cordelia', '63598 Lake View Lane');
insert into estaciones (id_estacion, nombre, direccion) values (82, 'Daystar', '55274 Kingsford Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (83, 'Memorial', '09 Birchwood Way');
insert into estaciones (id_estacion, nombre, direccion) values (84, 'Main', '4 New Castle Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (85, 'Meadow Ridge', '576 Larry Hill');
insert into estaciones (id_estacion, nombre, direccion) values (86, 'Melby', '34 Fairview Circle');
insert into estaciones (id_estacion, nombre, direccion) values (87, 'Westridge', '6073 Canary Plaza');
insert into estaciones (id_estacion, nombre, direccion) values (88, 'Springview', '1723 4th Circle');
insert into estaciones (id_estacion, nombre, direccion) values (89, 'Arizona', '8 Blackbird Point');
insert into estaciones (id_estacion, nombre, direccion) values (90, 'Vera', '23 Kennedy Hill');
insert into estaciones (id_estacion, nombre, direccion) values (91, 'Crowley', '5048 Northview Road');
insert into estaciones (id_estacion, nombre, direccion) values (92, 'Glendale', '4 North Parkway');
insert into estaciones (id_estacion, nombre, direccion) values (93, 'Arkansas', '30428 Ridgeview Circle');
insert into estaciones (id_estacion, nombre, direccion) values (94, 'Carpenter', '94 Rutledge Alley');
insert into estaciones (id_estacion, nombre, direccion) values (95, 'Nova', '798 Fordem Alley');
insert into estaciones (id_estacion, nombre, direccion) values (96, 'Green Ridge', '3 Brown Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (97, 'Twin Pines', '0 Stephen Circle');
insert into estaciones (id_estacion, nombre, direccion) values (98, 'Spenser', '6829 Brown Court');
insert into estaciones (id_estacion, nombre, direccion) values (99, 'Pepper Wood', '08641 Dwight Street');
insert into estaciones (id_estacion, nombre, direccion) values (100, 'Mifflin', '0 Hintze Point');
insert into estaciones (id_estacion, nombre, direccion) values (101, 'Springview', '780 Melrose Street');
insert into estaciones (id_estacion, nombre, direccion) values (102, 'Bluestem', '66 Lakewood Gardens Trail');
insert into estaciones (id_estacion, nombre, direccion) values (103, 'Bobwhite', '47681 Summit Trail');
insert into estaciones (id_estacion, nombre, direccion) values (104, 'Longview', '77 Fallview Street');
insert into estaciones (id_estacion, nombre, direccion) values (105, 'Carioca', '01 Loeprich Hill');
insert into estaciones (id_estacion, nombre, direccion) values (106, 'Calypso', '911 Melby Pass');
insert into estaciones (id_estacion, nombre, direccion) values (107, 'Meadow Valley', '51 Montana Park');
insert into estaciones (id_estacion, nombre, direccion) values (108, 'Union', '8 Holy Cross Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (109, 'Hollow Ridge', '8 International Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (110, 'Kings', '40489 Esker Pass');
insert into estaciones (id_estacion, nombre, direccion) values (111, 'Raven', '0934 Crowley Circle');
insert into estaciones (id_estacion, nombre, direccion) values (112, 'Helena', '850 Riverside Point');
insert into estaciones (id_estacion, nombre, direccion) values (113, 'Menomonie', '947 Loftsgordon Drive');
insert into estaciones (id_estacion, nombre, direccion) values (114, 'Shelley', '0 Havey Lane');
insert into estaciones (id_estacion, nombre, direccion) values (115, 'Corben', '31669 Manley Street');
insert into estaciones (id_estacion, nombre, direccion) values (116, 'Dakota', '791 Kingsford Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (117, 'American Ash', '8 Thompson Junction');
insert into estaciones (id_estacion, nombre, direccion) values (118, 'Lunder', '52 Hagan Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (119, 'Manitowish', '22773 Grayhawk Park');
insert into estaciones (id_estacion, nombre, direccion) values (120, 'Schiller', '249 Prairieview Junction');
insert into estaciones (id_estacion, nombre, direccion) values (121, 'Elgar', '53 Maple Wood Drive');
insert into estaciones (id_estacion, nombre, direccion) values (122, 'Bobwhite', '6 Declaration Street');
insert into estaciones (id_estacion, nombre, direccion) values (123, 'Maryland', '3 Surrey Place');
insert into estaciones (id_estacion, nombre, direccion) values (124, 'Corscot', '512 Leroy Lane');
insert into estaciones (id_estacion, nombre, direccion) values (125, 'Longview', '3394 Corry Center');
insert into estaciones (id_estacion, nombre, direccion) values (126, 'Nancy', '5596 Sugar Center');
insert into estaciones (id_estacion, nombre, direccion) values (127, 'Ruskin', '624 Sundown Drive');
insert into estaciones (id_estacion, nombre, direccion) values (128, 'Upham', '4719 Thackeray Parkway');
insert into estaciones (id_estacion, nombre, direccion) values (129, 'Buena Vista', '85 Nevada Circle');
insert into estaciones (id_estacion, nombre, direccion) values (130, 'Weeping Birch', '1131 Linden Way');
insert into estaciones (id_estacion, nombre, direccion) values (131, 'Claremont', '3431 Anzinger Way');
insert into estaciones (id_estacion, nombre, direccion) values (132, 'American Ash', '4058 Starling Park');
insert into estaciones (id_estacion, nombre, direccion) values (133, 'Sheridan', '534 1st Park');
insert into estaciones (id_estacion, nombre, direccion) values (134, 'Northview', '89 Lien Circle');
insert into estaciones (id_estacion, nombre, direccion) values (135, '5th', '254 Autumn Leaf Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (136, 'Talisman', '66 Longview Hill');
insert into estaciones (id_estacion, nombre, direccion) values (137, 'Bunker Hill', '54 Claremont Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (138, 'Scofield', '703 Lakewood Gardens Park');
insert into estaciones (id_estacion, nombre, direccion) values (139, 'Goodland', '7 Spenser Trail');
insert into estaciones (id_estacion, nombre, direccion) values (140, 'Redwing', '9144 Elgar Way');
insert into estaciones (id_estacion, nombre, direccion) values (141, 'Vera', '593 Iowa Court');
insert into estaciones (id_estacion, nombre, direccion) values (142, 'Heffernan', '9276 Sugar Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (143, 'Bowman', '9113 Gina Way');
insert into estaciones (id_estacion, nombre, direccion) values (144, 'Roxbury', '1 Claremont Park');
insert into estaciones (id_estacion, nombre, direccion) values (145, 'Menomonie', '2 Carey Way');
insert into estaciones (id_estacion, nombre, direccion) values (146, 'Paget', '5026 Elgar Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (147, 'Roxbury', '192 Menomonie Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (148, 'Oak Valley', '95 Maryland Court');
insert into estaciones (id_estacion, nombre, direccion) values (149, 'Hermina', '955 Heffernan Drive');
insert into estaciones (id_estacion, nombre, direccion) values (150, 'Ilene', '77174 Brickson Park Drive');
insert into estaciones (id_estacion, nombre, direccion) values (151, 'Lakewood', '82 Aberg Way');
insert into estaciones (id_estacion, nombre, direccion) values (152, 'Quincy', '6368 Tony Hill');
insert into estaciones (id_estacion, nombre, direccion) values (153, 'Kenwood', '0 Mosinee Trail');
insert into estaciones (id_estacion, nombre, direccion) values (154, 'Browning', '4 Reindahl Point');
insert into estaciones (id_estacion, nombre, direccion) values (155, 'Corry', '59 Del Mar Hill');
insert into estaciones (id_estacion, nombre, direccion) values (156, 'Haas', '775 Montana Alley');
insert into estaciones (id_estacion, nombre, direccion) values (157, 'Scofield', '75 Carey Lane');
insert into estaciones (id_estacion, nombre, direccion) values (158, 'Graedel', '45 Cordelia Street');
insert into estaciones (id_estacion, nombre, direccion) values (159, 'Dottie', '24 Fordem Point');
insert into estaciones (id_estacion, nombre, direccion) values (160, 'Victoria', '9048 Cherokee Park');
insert into estaciones (id_estacion, nombre, direccion) values (161, 'Carberry', '9 Anthes Place');
insert into estaciones (id_estacion, nombre, direccion) values (162, 'Lakewood', '58114 Butternut Place');
insert into estaciones (id_estacion, nombre, direccion) values (163, 'Hazelcrest', '31020 Grover Place');
insert into estaciones (id_estacion, nombre, direccion) values (164, 'Glacier Hill', '6 Petterle Trail');
insert into estaciones (id_estacion, nombre, direccion) values (165, 'Carioca', '401 Birchwood Point');
insert into estaciones (id_estacion, nombre, direccion) values (166, 'Blackbird', '69926 Northport Center');
insert into estaciones (id_estacion, nombre, direccion) values (167, 'Mallard', '2 Schlimgen Junction');
insert into estaciones (id_estacion, nombre, direccion) values (168, 'Northport', '07367 Helena Pass');
insert into estaciones (id_estacion, nombre, direccion) values (169, 'Union', '45589 Loftsgordon Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (170, 'Hudson', '6 Linden Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (171, 'Hoard', '6894 3rd Circle');
insert into estaciones (id_estacion, nombre, direccion) values (172, 'Park Meadow', '79865 Jackson Street');
insert into estaciones (id_estacion, nombre, direccion) values (173, 'Monterey', '1547 Knutson Drive');
insert into estaciones (id_estacion, nombre, direccion) values (174, 'Brentwood', '15046 Spaight Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (175, 'David', '53 Milwaukee Parkway');
insert into estaciones (id_estacion, nombre, direccion) values (176, 'Orin', '1 Oakridge Way');
insert into estaciones (id_estacion, nombre, direccion) values (177, 'Toban', '0 Rowland Street');
insert into estaciones (id_estacion, nombre, direccion) values (178, 'Steensland', '56456 Oriole Way');
insert into estaciones (id_estacion, nombre, direccion) values (179, 'Cherokee', '676 Waywood Pass');
insert into estaciones (id_estacion, nombre, direccion) values (180, 'Washington', '0287 Aberg Road');
insert into estaciones (id_estacion, nombre, direccion) values (181, 'Maple Wood', '760 Muir Lane');
insert into estaciones (id_estacion, nombre, direccion) values (182, 'Barnett', '0 Iowa Center');
insert into estaciones (id_estacion, nombre, direccion) values (183, 'Graedel', '35 Talisman Place');
insert into estaciones (id_estacion, nombre, direccion) values (184, 'Clemons', '990 Donald Lane');
insert into estaciones (id_estacion, nombre, direccion) values (185, 'Tomscot', '02 Lukken Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (186, 'Maywood', '4518 Russell Court');
insert into estaciones (id_estacion, nombre, direccion) values (187, 'Karstens', '281 Sullivan Drive');
insert into estaciones (id_estacion, nombre, direccion) values (188, 'Ridge Oak', '5709 Lotheville Point');
insert into estaciones (id_estacion, nombre, direccion) values (189, 'Forster', '1 Armistice Parkway');
insert into estaciones (id_estacion, nombre, direccion) values (190, 'Carey', '418 Lakewood Gardens Drive');
insert into estaciones (id_estacion, nombre, direccion) values (191, 'Memorial', '251 Sachs Trail');
insert into estaciones (id_estacion, nombre, direccion) values (192, 'Schmedeman', '8 Transport Lane');
insert into estaciones (id_estacion, nombre, direccion) values (193, 'Holy Cross', '32921 Hoard Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (194, 'Stoughton', '59 Sunbrook Park');
insert into estaciones (id_estacion, nombre, direccion) values (195, 'Johnson', '03 Starling Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (196, 'Wayridge', '5 Valley Edge Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (197, 'Green', '2420 Gale Park');
insert into estaciones (id_estacion, nombre, direccion) values (198, 'Banding', '2 Farragut Plaza');
insert into estaciones (id_estacion, nombre, direccion) values (199, 'Sutteridge', '70 Lukken Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (200, 'Killdeer', '474 Pearson Place');
insert into estaciones (id_estacion, nombre, direccion) values (201, 'Packers', '2963 Jenifer Way');
insert into estaciones (id_estacion, nombre, direccion) values (202, 'Service', '9 Bluestem Junction');
insert into estaciones (id_estacion, nombre, direccion) values (203, 'Butternut', '6036 Oriole Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (204, 'Waubesa', '79240 Kim Center');
insert into estaciones (id_estacion, nombre, direccion) values (205, 'Warner', '16388 Kennedy Parkway');
insert into estaciones (id_estacion, nombre, direccion) values (206, 'Barby', '808 Comanche Court');
insert into estaciones (id_estacion, nombre, direccion) values (207, 'Burrows', '77452 Summer Ridge Drive');
insert into estaciones (id_estacion, nombre, direccion) values (208, 'Brown', '387 Division Way');
insert into estaciones (id_estacion, nombre, direccion) values (209, 'Nova', '2 Crownhardt Trail');
insert into estaciones (id_estacion, nombre, direccion) values (210, 'Pine View', '423 Killdeer Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (211, 'Westend', '576 Anniversary Drive');
insert into estaciones (id_estacion, nombre, direccion) values (212, 'Meadow Vale', '04208 Reindahl Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (213, 'Trailsway', '5 Drewry Park');
insert into estaciones (id_estacion, nombre, direccion) values (214, 'Springs', '97738 Brentwood Road');
insert into estaciones (id_estacion, nombre, direccion) values (215, 'Memorial', '37 Village Court');
insert into estaciones (id_estacion, nombre, direccion) values (216, 'Pawling', '07359 Thierer Point');
insert into estaciones (id_estacion, nombre, direccion) values (217, 'Arkansas', '32 Schiller Drive');
insert into estaciones (id_estacion, nombre, direccion) values (218, 'Erie', '8490 Mallory Hill');
insert into estaciones (id_estacion, nombre, direccion) values (219, 'Fordem', '4 Cody Way');
insert into estaciones (id_estacion, nombre, direccion) values (220, 'Summer Ridge', '760 Melody Park');
insert into estaciones (id_estacion, nombre, direccion) values (221, 'Jay', '16669 Roth Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (222, 'Del Mar', '481 Lindbergh Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (223, 'Derek', '15 Declaration Plaza');
insert into estaciones (id_estacion, nombre, direccion) values (224, 'Portage', '3595 Utah Junction');
insert into estaciones (id_estacion, nombre, direccion) values (225, 'Algoma', '423 Valley Edge Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (226, 'Darwin', '2825 Duke Lane');
insert into estaciones (id_estacion, nombre, direccion) values (227, 'Bellgrove', '9 Dorton Pass');
insert into estaciones (id_estacion, nombre, direccion) values (228, 'Melvin', '26755 Tony Hill');
insert into estaciones (id_estacion, nombre, direccion) values (229, 'Crowley', '10728 Grim Trail');
insert into estaciones (id_estacion, nombre, direccion) values (230, 'Fuller', '4470 Milwaukee Alley');
insert into estaciones (id_estacion, nombre, direccion) values (231, 'Huxley', '01 Fulton Alley');
insert into estaciones (id_estacion, nombre, direccion) values (232, 'Village', '9 Forest Run Pass');
insert into estaciones (id_estacion, nombre, direccion) values (233, 'Sachtjen', '2751 Badeau Street');
insert into estaciones (id_estacion, nombre, direccion) values (234, 'Canary', '15220 Spohn Junction');
insert into estaciones (id_estacion, nombre, direccion) values (235, 'Stuart', '282 Mockingbird Parkway');
insert into estaciones (id_estacion, nombre, direccion) values (236, 'Londonderry', '1 Garrison Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (237, 'Cardinal', '6389 Michigan Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (238, 'Main', '5 Rieder Junction');
insert into estaciones (id_estacion, nombre, direccion) values (239, 'Sutherland', '53 High Crossing Center');
insert into estaciones (id_estacion, nombre, direccion) values (240, 'Crowley', '705 Beilfuss Street');
insert into estaciones (id_estacion, nombre, direccion) values (241, 'Walton', '3744 Oneill Street');
insert into estaciones (id_estacion, nombre, direccion) values (242, 'Lindbergh', '497 Starling Place');
insert into estaciones (id_estacion, nombre, direccion) values (243, 'Pepper Wood', '34 Birchwood Park');
insert into estaciones (id_estacion, nombre, direccion) values (244, 'Bowman', '67 Dapin Lane');
insert into estaciones (id_estacion, nombre, direccion) values (245, 'Graceland', '337 Jay Hill');
insert into estaciones (id_estacion, nombre, direccion) values (246, 'Ramsey', '504 Kingsford Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (247, 'Barnett', '5264 Darwin Road');
insert into estaciones (id_estacion, nombre, direccion) values (248, 'Bayside', '992 Stone Corner Street');
insert into estaciones (id_estacion, nombre, direccion) values (249, 'Meadow Vale', '08 Lakeland Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (250, 'Declaration', '9066 Eagle Crest Way');
insert into estaciones (id_estacion, nombre, direccion) values (251, 'Fulton', '71687 Pine View Place');
insert into estaciones (id_estacion, nombre, direccion) values (252, 'Sommers', '9880 Pleasure Junction');
insert into estaciones (id_estacion, nombre, direccion) values (253, 'Colorado', '6 Pennsylvania Center');
insert into estaciones (id_estacion, nombre, direccion) values (254, 'Utah', '325 Redwing Road');
insert into estaciones (id_estacion, nombre, direccion) values (255, 'Stephen', '467 Morning Center');
insert into estaciones (id_estacion, nombre, direccion) values (256, 'Fallview', '539 Magdeline Circle');
insert into estaciones (id_estacion, nombre, direccion) values (257, 'Marcy', '5313 Cordelia Pass');
insert into estaciones (id_estacion, nombre, direccion) values (258, 'Paget', '489 Jenna Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (259, 'Kinsman', '5 Schurz Point');
insert into estaciones (id_estacion, nombre, direccion) values (260, 'Summer Ridge', '69587 Bluejay Center');
insert into estaciones (id_estacion, nombre, direccion) values (261, 'Towne', '75554 Pierstorff Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (262, 'Bunker Hill', '60312 La Follette Trail');
insert into estaciones (id_estacion, nombre, direccion) values (263, 'Forest', '773 Dawn Street');
insert into estaciones (id_estacion, nombre, direccion) values (264, 'Wayridge', '0397 Warner Alley');
insert into estaciones (id_estacion, nombre, direccion) values (265, 'Hollow Ridge', '6819 Oak Court');
insert into estaciones (id_estacion, nombre, direccion) values (266, 'Southridge', '3634 Green Ridge Road');
insert into estaciones (id_estacion, nombre, direccion) values (267, 'Butterfield', '41298 Becker Junction');
insert into estaciones (id_estacion, nombre, direccion) values (268, 'Mallory', '53 Forest Run Plaza');
insert into estaciones (id_estacion, nombre, direccion) values (269, 'Almo', '4324 Golden Leaf Lane');
insert into estaciones (id_estacion, nombre, direccion) values (270, 'Graedel', '49 Iowa Junction');
insert into estaciones (id_estacion, nombre, direccion) values (271, 'Stuart', '229 Utah Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (272, 'Summer Ridge', '5 Oxford Trail');
insert into estaciones (id_estacion, nombre, direccion) values (273, 'Knutson', '46435 Atwood Court');
insert into estaciones (id_estacion, nombre, direccion) values (274, 'Sommers', '105 High Crossing Junction');
insert into estaciones (id_estacion, nombre, direccion) values (275, 'Fieldstone', '4631 Lunder Road');
insert into estaciones (id_estacion, nombre, direccion) values (276, 'Kennedy', '0 Vidon Drive');
insert into estaciones (id_estacion, nombre, direccion) values (277, 'Shelley', '61329 Fieldstone Plaza');
insert into estaciones (id_estacion, nombre, direccion) values (278, 'Crest Line', '79210 Montana Drive');
insert into estaciones (id_estacion, nombre, direccion) values (279, 'Corben', '9 Ronald Regan Street');
insert into estaciones (id_estacion, nombre, direccion) values (280, 'Corben', '24 Acker Terrace');
insert into estaciones (id_estacion, nombre, direccion) values (281, 'Katie', '840 Jenna Crossing');
insert into estaciones (id_estacion, nombre, direccion) values (282, 'Clemons', '56 Sunfield Trail');
insert into estaciones (id_estacion, nombre, direccion) values (283, 'Prairie Rose', '27824 Schmedeman Plaza');
insert into estaciones (id_estacion, nombre, direccion) values (284, 'Everett', '4499 Old Shore Drive');
insert into estaciones (id_estacion, nombre, direccion) values (285, 'Debs', '439 West Way');
insert into estaciones (id_estacion, nombre, direccion) values (286, 'Thackeray', '526 Susan Place');
insert into estaciones (id_estacion, nombre, direccion) values (287, 'American', '3 Lakewood Gardens Hill');
insert into estaciones (id_estacion, nombre, direccion) values (288, 'Village', '6 Golden Leaf Pass');
insert into estaciones (id_estacion, nombre, direccion) values (289, 'School', '681 Kipling Street');
insert into estaciones (id_estacion, nombre, direccion) values (290, 'Johnson', '9000 Melvin Park');
insert into estaciones (id_estacion, nombre, direccion) values (291, 'Kinsman', '34 Sunbrook Alley');
insert into estaciones (id_estacion, nombre, direccion) values (292, 'Oriole', '2656 Paget Junction');
insert into estaciones (id_estacion, nombre, direccion) values (293, 'Granby', '5954 Heffernan Point');
insert into estaciones (id_estacion, nombre, direccion) values (294, 'Michigan', '4 Bunker Hill Avenue');
insert into estaciones (id_estacion, nombre, direccion) values (295, 'Merchant', '4 Ridge Oak Alley');
insert into estaciones (id_estacion, nombre, direccion) values (296, 'Morning', '3 Darwin Lane');
insert into estaciones (id_estacion, nombre, direccion) values (297, 'Superior', '36601 Fisk Hill');
insert into estaciones (id_estacion, nombre, direccion) values (298, 'Di Loreto', '4 Northridge Pass');
insert into estaciones (id_estacion, nombre, direccion) values (299, 'Mariners Cove', '15 Cambridge Trail');
insert into estaciones (id_estacion, nombre, direccion) values (300, 'Bayside', '22 Susan Circle');
