insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (1, 11, 30, 'Strange Case of Dr. Jekyll and Miss Osbourne, The (Dr. Jekyll and His Women) (Docteur Jekyll et les femmes)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (2, 10, 36, 'How to Be a Man');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (3, 92, 9, '12:08 East of Bucharest (A fost sau n-a fost?)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (4, 90, 4, 'Lost in the Desert');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (5, 19, 42, 'Bugmaster (Mushishi)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (6, 226, 21, 'La liga no es cosa de hombres');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (7, 65, 10, 'The Year Without a Santa Claus');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (8, 192, 47, 'Profit, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (9, 267, 12, 'Man in the Saddle');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (10, 277, 14, 'Prairie Home Companion, A');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (11, 35, 17, 'Godzilla vs. Hedorah (Gojira tai Hedorâ) (Godzilla vs. The Smog Monster) ');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (12, 6, 48, 'Bachelor Party');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (13, 116, 32, 'United');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (14, 100, 36, 'Year of the Yao, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (15, 255, 17, 'Batman: Gotham Knight');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (16, 231, 24, 'One Night Stand');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (17, 13, 23, 'Bianca Beauchamp: All Access');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (18, 49, 13, 'Very Good Girls');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (19, 279, 22, 'Facing Windows (Finestra di fronte, La)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (20, 287, 47, 'Pet, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (21, 282, 42, 'Seal Team Eight: Behind Enemy Lines');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (22, 142, 1, 'One Day in September');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (23, 44, 23, '18 Again!');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (24, 63, 39, 'Libre échange');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (25, 261, 13, 'Paradise Lost 2: Revelations');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (26, 56, 47, 'Forever Mine');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (27, 264, 21, 'Lavender Hill Mob, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (28, 291, 34, 'Fubar');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (29, 138, 44, 'History Is Made at Night');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (30, 174, 20, 'Bat, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (31, 16, 31, 'Pursuit of Unhappiness, The (Anleitung zum Unglücklichsein)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (32, 287, 29, 'Breathing Fire');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (33, 82, 26, 'Oyster Farmer');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (34, 259, 32, 'Snakehead Terror');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (35, 165, 33, 'Bloodfist');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (36, 231, 25, 'Night of the Day of the Dawn of the Son of the Bride of the Return of the Terror');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (37, 41, 48, 'Men with Guns');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (38, 253, 2, 'Black Snake Moan');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (39, 284, 47, 'Resident Evil: Damnation');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (40, 239, 24, 'Heima');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (41, 172, 17, 'Death by China ');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (42, 136, 42, 'Moving');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (43, 218, 45, 'A Second Chance');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (44, 87, 4, 'Frances');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (45, 31, 6, 'Which Way Is the Front Line From Here?  The Life and Time of Tim Hetherington');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (46, 292, 13, 'Rising Place, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (47, 17, 43, 'Making ''The New World''');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (48, 243, 14, 'One Million Years B.C.');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (49, 258, 30, 'Black Butterflies');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (50, 3, 46, 'Dragonfly');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (51, 32, 9, 'Father of the Bride');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (52, 76, 31, 'What Have They Done to Your Daughters?');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (53, 72, 8, 'Support Your Local Gunfighter');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (54, 293, 30, 'Adventure of Sherlock Holmes'' Smarter Brother, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (55, 161, 9, 'Losers'' Club (Kaybedenler kulübü)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (56, 267, 42, 'Alabama Moon');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (57, 6, 45, 'Stone Reader');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (58, 105, 14, 'My Father and My Son (Babam ve oglum)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (59, 247, 11, 'Undercover Brother');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (60, 187, 3, 'A Night in the Show');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (61, 110, 16, 'Son of Batman');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (62, 88, 24, 'Vamp');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (63, 145, 42, 'Perfect World, A');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (64, 234, 36, 'Bang, Bang, You''re Dead');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (65, 118, 18, 'Ex-Girlfriends');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (66, 35, 10, 'What Have You Done to Solange?');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (67, 6, 42, 'Black Swan, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (68, 84, 49, 'Aladdin');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (69, 20, 44, 'Wild Target');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (70, 72, 50, 'Ten Canoes');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (71, 299, 29, 'American Pimp');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (72, 115, 4, 'More');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (73, 167, 12, 'Deadly Blessing');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (74, 14, 23, 'Free Enterprise');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (75, 96, 45, 'One Piece Film: Strong World');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (76, 33, 46, 'Horrible Bosses');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (77, 277, 31, 'Juha');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (78, 85, 46, 'Kermit''s Swamp Years');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (79, 123, 15, 'Street Mobster (a.k.a. Modern Yakuza: Outlaw Killer) (Gendai yakuza: hito-kiri yota)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (80, 258, 45, 'I''m Gonna Git You Sucka');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (81, 147, 33, 'American: The Bill Hicks Story');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (82, 232, 4, 'Hunt vs Lauda: F1''s Greatest Racing Rivals');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (83, 193, 13, 'Shirin in Love');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (84, 272, 41, 'Object of Beauty, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (85, 125, 31, 'Fast Food, Fast Women');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (86, 114, 25, 'Araya');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (87, 161, 34, 'Samoure');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (88, 300, 50, 'Spare Parts');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (89, 217, 17, 'The Adventures of Tom Thumb & Thumbelina');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (90, 53, 22, 'Chump at Oxford, A');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (91, 203, 24, 'Anthropophagus: The Grim Reaper (Antropophagus) (Man Beast) (Savage Island, The) (Zombie''s Rage, The)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (92, 276, 21, 'Camille Rewinds');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (93, 298, 46, 'Beast of War, The (Beast, The)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (94, 188, 47, 'Haunted Echoes');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (95, 282, 13, 'Phantom Stagecoach, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (96, 85, 36, 'Hour of the Gun');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (97, 255, 38, 'Audrey Rose');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (98, 199, 42, 'Falling Down');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (99, 251, 41, 'Razor''s Edge, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (100, 96, 7, 'Close to Leo (Tout contre Léo)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (101, 283, 22, 'Stick It');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (102, 239, 25, 'Woman in the Dunes (Suna no onna)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (103, 51, 20, 'Infamous');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (104, 179, 19, 'Come Early Morning');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (105, 179, 9, 'Jubilee');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (106, 51, 1, 'Lola');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (107, 111, 28, 'K-20: The Fiend with Twenty Faces');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (108, 278, 49, 'Far Side of the Moon, The (Face cachée de la lune, La)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (109, 229, 14, 'Man with the Movie Camera, The (Chelovek s kino-apparatom)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (110, 232, 2, 'Appleseed (Appurushîdo)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (111, 127, 43, 'This So-Called Disaster');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (112, 149, 48, 'Broken');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (113, 98, 24, 'Highly Dangerous');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (114, 228, 49, 'Belly 2: Millionaire Boyz Club');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (115, 233, 27, 'World War Z');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (116, 179, 12, 'Queen to Play (Joueuse)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (117, 295, 13, 'Audition (Konkurs)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (118, 65, 46, 'Unlawful Entry');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (119, 140, 26, 'Cube');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (120, 85, 32, 'Sweeney Todd: The Demon Barber of Fleet Street');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (121, 5, 47, '1000 Journals');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (122, 148, 35, ' Days of Summer');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (123, 164, 27, 'Spirit of the Beehive, The (Espíritu de la colmena, El)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (124, 33, 35, '49 Up');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (125, 209, 41, 'Jubilee');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (126, 28, 8, 'Stella Does Tricks');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (127, 264, 12, 'Cass');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (128, 291, 22, 'Pusher');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (129, 205, 1, 'Grandpa for Christmas, A (Bert & Becca)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (130, 87, 37, 'Zoom');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (131, 154, 29, 'Marshland (Isla mínima, La)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (132, 109, 50, 'Topkapi');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (133, 21, 37, 'Party Girl');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (134, 273, 28, 'Bitch Slap');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (135, 215, 33, 'Manta, Manta');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (136, 242, 10, 'Falcon and the Snowman, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (137, 201, 18, 'Show Me');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (138, 48, 10, 'Kind Lady');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (139, 200, 40, 'Ivan the Terrible, Part One (Ivan Groznyy I)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (140, 95, 32, 'Woman, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (141, 187, 14, 'Surviving Desire');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (142, 3, 3, 'Atlas Shrugged: Who Is John Galt? (Atlas Shrugged: Part III)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (143, 104, 9, 'Sweeney, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (144, 237, 31, 'Shanks');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (145, 212, 49, 'Louis C.K.: Chewed Up');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (146, 279, 20, 'Cocaine Cowboys II: Hustlin'' With the Godmother');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (147, 298, 14, 'American Virgin');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (148, 229, 12, 'Slaves to the Underground');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (149, 173, 36, 'Kisses (Kuchizuke)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (150, 237, 27, 'Coming to America');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (151, 94, 17, 'Prince of Persia: The Sands of Time');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (152, 63, 21, 'My Week with Marilyn');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (153, 227, 4, 'Habana Blues');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (154, 241, 44, 'Journey of Natty Gann, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (155, 231, 45, 'Promised Land');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (156, 120, 42, 'American Heart');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (157, 64, 38, 'Louis C.K.: Shameless');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (158, 125, 18, 'Putty Hill');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (159, 147, 41, 'Twister');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (160, 273, 31, 'Dolphin Tale');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (161, 215, 18, 'Camille Rewinds');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (162, 300, 13, 'Short Film About Love, A (Krótki film o milosci)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (163, 42, 24, 'Short Circuit');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (164, 293, 46, 'Siberia');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (165, 48, 7, 'Two Can Play That Game');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (166, 139, 36, 'Dark at the Top of the Stairs, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (167, 153, 23, '20,000 Leagues Under the Sea');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (168, 53, 21, 'Naked Edge, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (169, 111, 32, 'Grizzly Man');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (170, 40, 12, 'Road to Singapore');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (171, 202, 13, 'Special Delivery');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (172, 299, 29, 'Rape Me (Baise-moi)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (173, 220, 34, 'Nightmare Factory');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (174, 218, 45, 'The Learning Tree');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (175, 216, 27, 'Gotcha!');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (176, 175, 26, 'Sugar Hill');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (177, 125, 14, 'C.H.O.M.P.S.');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (178, 171, 46, 'Cape No. 7 (Hái-kak chhit-ho)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (179, 38, 50, 'I Remember Mama');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (180, 1, 42, 'Patrice O''Neal: Elephant in the Room');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (181, 44, 42, 'Confess');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (182, 256, 29, 'Beauty in Trouble (Kráska v nesnázích)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (183, 182, 29, 'Love (Szerelem)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (184, 146, 6, 'Carriers');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (185, 179, 27, 'Ghost Dad');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (186, 86, 20, 'New Kind of Love, A');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (187, 83, 2, 'Bad News Bears');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (188, 45, 20, 'Sacrifice (Zhao shi gu er)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (189, 284, 11, 'Paintball');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (190, 233, 43, 'Love in Bloom');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (191, 17, 17, 'Mood Indigo (L''écume des jours)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (192, 227, 12, 'Other Side of Midnight, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (193, 65, 25, 'MacGruber');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (194, 9, 15, 'Beneath the Dark');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (195, 29, 31, 'Peter''s Friends');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (196, 186, 6, 'Groundhog Day');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (197, 297, 22, 'All or Nothing');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (198, 220, 2, 'Deep Blue Sea, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (199, 227, 12, 'Navy Seals');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (200, 137, 45, 'Shakedown');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (201, 36, 18, 'The Beautiful Story');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (202, 197, 5, 'Kwaidan (Kaidan)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (203, 244, 17, 'Il Capitano');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (204, 103, 33, 'Horror of the Zombies');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (205, 156, 3, 'Paranoia');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (206, 212, 3, 'Coven');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (207, 85, 2, 'Johnny Apollo');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (208, 144, 19, 'Juvenile Court');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (209, 183, 35, 'How to Make Love to a Woman');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (210, 213, 9, 'Children of the Corn IV: The Gathering');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (211, 174, 36, 'Mammuth');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (212, 138, 19, 'The Fool');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (213, 256, 42, 'Haunted Castle');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (214, 176, 19, 'Megan Is Missing');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (215, 233, 19, 'Beaches of Agnes, The (Plages d''Agnès, Les)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (216, 107, 3, 'Peter and Vandy');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (217, 123, 36, 'Impulse');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (218, 82, 39, 'Ernest Rides Again');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (219, 47, 8, 'Space Battleship Yamato');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (220, 123, 28, 'Julius Caesar');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (221, 62, 8, 'Dracula');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (222, 260, 15, 'Blindsight');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (223, 91, 34, 'Orderers (Les ordres)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (224, 230, 38, 'Arthur and the Revenge of Maltazard (Arthur et la vengeance de Maltazard)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (225, 298, 30, 'Sleeping Beauty, The (La belle endormie)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (226, 237, 35, 'Tale of Two Cities, A');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (227, 140, 45, 'Drawing Restraint 9');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (228, 230, 34, 'Shadow Kill');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (229, 134, 49, 'Stealing Rembrandt (Rembrandt)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (230, 110, 49, 'Next of Kin');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (231, 15, 25, 'Crazy Mama');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (232, 48, 43, 'Hart''s War');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (233, 163, 42, 'A Blank on the Map');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (234, 291, 18, 'Going to Pieces: The Rise and Fall of the Slasher Film');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (235, 186, 12, 'Ciao, Professore! (Io speriamo che me la cavo)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (236, 39, 32, 'Man Who Couldn''t Say No, The (Mies joka ei osannut sanoa EI)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (237, 58, 6, 'Ismael');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (238, 172, 45, 'Reckless');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (239, 207, 30, 'Eye Above the Well, The (Het oog boven de put)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (240, 199, 47, 'Macon County Line');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (241, 210, 18, 'Baby Boy');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (242, 116, 35, 'Son, The (Le fils)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (243, 128, 4, 'The Widow From Chicago');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (244, 55, 47, 'Three Smart Girls Grow Up');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (245, 263, 15, 'Mighty Aphrodite');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (246, 80, 12, 'Our Fathers');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (247, 253, 9, 'Mummy, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (248, 162, 27, 'Spark: A Burning Man Story');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (249, 210, 14, 'Loss of a Teardrop Diamond, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (250, 182, 33, 'Billy Two Hats (Lady and the Outlaw, The)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (251, 45, 42, 'She''s Having a Baby');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (252, 201, 18, 'Reaching for the Moon');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (253, 44, 44, 'Love Bites');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (254, 290, 40, 'Good Marriage, A (Beau mariage, Le)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (255, 224, 4, 'Farmer & Chase');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (256, 114, 27, 'Donovan''s Echo');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (257, 223, 36, 'Daughters of the Dust');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (258, 4, 24, 'Victory');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (259, 190, 20, 'Babette Goes to War');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (260, 199, 42, 'Louis C.K.: Shameless');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (261, 274, 43, 'Fate (Yazgi)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (262, 49, 32, 'Long Day''s Journey Into Night');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (263, 57, 42, 'Land That Time Forgot, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (264, 101, 45, 'Louis C.K.: Live at The Comedy Store');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (265, 114, 8, 'Burning Palms');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (266, 254, 5, 'Jack the Bear');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (267, 259, 4, 'Free Radicals:  A History of Experimental Film');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (268, 66, 46, 'At Middleton');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (269, 24, 5, 'The Shoe');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (270, 298, 24, 'Hope and Glory');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (271, 171, 47, 'Casino Royale');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (272, 285, 22, 'Ballad of the Sad Cafe, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (273, 128, 44, 'Lulu in Berlin');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (274, 245, 35, '10');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (275, 179, 1, 'Matriarch, The (Lieksa!)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (276, 228, 17, 'I Will Follow You Into the Dark');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (277, 67, 4, 'Moolaadé');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (278, 44, 49, 'Johnny Apollo');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (279, 275, 35, 'Perfect Score, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (280, 28, 42, 'Ghoulies IV');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (281, 211, 1, 'Hasty Heart, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (282, 196, 50, 'Three Little Words');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (283, 46, 11, 'Nibelungen: Kriemhild''s Revenge, Die (Die Nibelungen: Kriemhilds Rache)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (284, 30, 49, 'Stendhal Syndrome, The (Sindrome di Stendhal, La)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (285, 109, 9, 'Charlie and the Chocolate Factory');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (286, 9, 2, 'Bend It Like Beckham');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (287, 5, 47, 'Harrison''s Flowers');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (288, 5, 27, 'Facing Ali');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (289, 98, 3, 'Goofy Movie, A');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (290, 222, 6, 'The Mummy''s Shroud');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (291, 148, 44, 'Likeable Mister R, The (Simpaticul domn R)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (292, 8, 27, 'Love Exposure (Ai No Mukidashi)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (293, 185, 13, 'Caterina in the Big City (Caterina va in città)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (294, 194, 36, 'Romance & Cigarettes');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (295, 275, 49, 'Yolki');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (296, 198, 13, 'Wrestling for Jesus: The Tale of T-Money');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (297, 245, 14, 'Flame and the Arrow, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (298, 142, 37, 'Taxi Driver');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (299, 86, 7, 'Babes in Toyland');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (300, 65, 6, 'Garage Olimpo');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (301, 14, 2, 'Big Bird Cage, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (302, 197, 8, 'The Epic of Everest');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (303, 290, 50, 'Burden of Dreams');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (304, 24, 17, 'Celine: Through the Eyes of the World');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (305, 9, 31, 'Absent-Minded Professor, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (306, 190, 5, 'Night Train Murders (Last Stop on the Night Train) (Ultimo treno della notte, L'')');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (307, 197, 23, 'Rewrite, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (308, 171, 32, 'Flame of New Orleans, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (309, 277, 6, 'Dinosaur');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (310, 136, 21, 'Elevator to the Gallows (a.k.a. Frantic) (Ascenseur pour l''échafaud)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (311, 120, 29, 'Sleepover');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (312, 28, 13, 'Something Real and Good');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (313, 71, 47, 'No Distance Left to Run');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (314, 88, 48, 'No Such Thing');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (315, 56, 23, 'Waiter (Ober)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (316, 9, 28, 'Innerspace');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (317, 70, 16, 'Never Forever');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (318, 256, 3, 'Who''s Your Daddy?');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (319, 213, 44, 'Twilight Saga: Eclipse, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (320, 227, 41, 'Crossing, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (321, 187, 19, 'Cleopatra');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (322, 294, 38, 'Too Many Husbands');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (323, 4, 23, 'Little Odessa');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (324, 192, 37, '''Neath the Arizona Skies');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (325, 97, 38, 'Bogowie');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (326, 154, 33, 'Primal Fear');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (327, 156, 39, 'Our Town');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (328, 189, 10, 'Broken Lance');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (329, 270, 5, 'Black Sunday (La maschera del demonio)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (330, 147, 7, 'Caught');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (331, 135, 12, 'Where the Red Fern Grows');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (332, 174, 37, 'Tarnished Angels, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (333, 253, 42, 'Speed 2: Cruise Control');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (334, 238, 35, 'Wyatt Earp');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (335, 229, 34, 'Tower Heist');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (336, 22, 32, 'Blade of the Ripper');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (337, 282, 22, 'Hipsters (Stilyagi)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (338, 53, 49, 'Good-bye, My Lady');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (339, 269, 15, 'Panic in Needle Park, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (340, 121, 29, 'Never Cry Wolf');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (341, 267, 31, 'The Runner from Ravenshead');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (342, 298, 42, '47  Ronin (Shijûshichinin no shikaku)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (343, 31, 47, 'Straight Talk');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (344, 224, 5, 'Mushrooming (Seenelkäik)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (345, 166, 26, 'Outlaw, The (Lope)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (346, 284, 6, 'Jumpin'' Jack Flash');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (347, 130, 9, 'Life Stinks');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (348, 91, 36, 'Dirty Dancing: Havana Nights');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (349, 72, 36, 'Rite, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (350, 299, 37, 'Nightmare');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (351, 92, 1, 'Mentor');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (352, 273, 42, 'Street with No Name, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (353, 18, 42, 'Fright Night Part II');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (354, 167, 9, 'Life Less Ordinary, A');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (355, 1, 6, 'Seeing Other People');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (356, 215, 7, 'For a Woman (Pour une femme)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (357, 250, 50, 'Blame It on Rio');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (358, 256, 43, 'Wicked City (Yôjû toshi)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (359, 41, 36, 'Gimme Shelter');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (360, 184, 42, 'Stonewall Uprising');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (361, 67, 9, 'Fallen Idol, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (362, 163, 43, 'Who''s Afraid of Virginia Woolf?');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (363, 253, 12, 'Intimidation');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (364, 151, 45, 'Valdez Is Coming');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (365, 166, 44, 'Holy Mountain, The (Montaña sagrada, La)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (366, 156, 43, 'Escape From Tomorrow');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (367, 67, 39, 'Avanti!');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (368, 109, 31, 'Dream Man');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (369, 94, 30, 'Vengeance is Mine (Fukushu suruwa wareniari)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (370, 85, 34, 'Laid To Rest');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (371, 81, 1, 'Nowhere to Hide (Injeong sajeong bol geot eobtda)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (372, 261, 5, 'A Blank on the Map');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (373, 69, 11, 'Dick Tracy vs. Cueball');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (374, 246, 17, 'Wadjda');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (375, 233, 44, 'Princess Tam-Tam (Princesse Tam-Tam)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (376, 244, 2, 'Magnum Cop');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (377, 170, 5, 'Man from the Future, The (O Homem do Futuro)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (378, 5, 26, 'Declaration of War (La Guerre est Déclarée)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (379, 62, 47, 'Greystoke: The Legend of Tarzan, Lord of the Apes');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (380, 73, 48, 'Midnight Crossing');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (381, 95, 49, 'My Summer of Love');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (382, 91, 40, 'Swing Vote');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (383, 153, 37, 'Johnny Apollo');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (384, 58, 48, 'Today''s Special');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (385, 90, 26, 'Bad Luck (Zezowate szczescie)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (386, 106, 11, 'Celine and Julie Go Boating (Celine et Julie vont en bateau)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (387, 56, 24, 'Helicopter String Quartet');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (388, 158, 49, 'Shark Attack');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (389, 93, 1, 'Blue Chips');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (390, 23, 42, 'Zulu Dawn');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (391, 261, 7, 'Brand Upon the Brain!');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (392, 249, 37, 'Some Kind of Hero');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (393, 211, 29, 'Welcome Mr. Marshall (Bienvenido Mister Marshall)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (394, 11, 28, 'Who Are the DeBolts? [And Where Did They Get 19 Kids?]');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (395, 55, 10, 'Cutie and the Boxer');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (396, 255, 5, 'Abbott and Costello in Hollywood');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (397, 248, 29, 'Prize Winner of Defiance Ohio, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (398, 225, 46, 'U.S. Marshals');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (399, 106, 48, 'Maniac Cop 2');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (400, 251, 10, 'True Heart');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (401, 186, 29, 'Safety Not Guaranteed');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (402, 24, 14, 'Every Night Dreams (Each Night I Dream) (Yogoto no yume)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (403, 166, 27, 'Sophie''s World (Sofies verden)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (404, 300, 7, 'Ingrid');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (405, 218, 26, 'Night Ambush (Ill Met by Moonlight)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (406, 108, 50, 'Genocide');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (407, 298, 26, 'Lie with Me');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (408, 175, 8, 'Boomerang');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (409, 162, 17, 'Manzanar Fishing Club, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (410, 57, 23, 'Level Five');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (411, 83, 29, 'Cimarron');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (412, 242, 50, 'The Stanford Prison Experiment');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (413, 201, 8, 'Bounty Hunters (Bail Enforcers)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (414, 189, 37, 'Rated X: A Journey Through Porn');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (415, 9, 27, 'Double Or Nothing');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (416, 187, 21, 'Shamrock Handicap, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (417, 127, 3, 'Young at Heart');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (418, 116, 3, 'Fireflies in the Garden');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (419, 9, 29, 'Dark Tide');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (420, 57, 21, 'Tyler Perry''s Madea Goes to Jail');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (421, 210, 31, 'Battle of Britain, The (Why We Fight, 4)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (422, 235, 26, 'The Six Million Dollar Man');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (423, 257, 34, 'Tribes');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (424, 62, 48, 'Fulltime Killer (Chuen jik sat sau)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (425, 92, 17, 'Ride Along');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (426, 56, 38, 'Hamlet');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (427, 145, 8, 'Tables Turned on the Gardener');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (428, 271, 28, 'Bonheur, Le');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (429, 247, 28, 'Bill Cosby, Himself');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (430, 79, 13, 'Artist, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (431, 29, 17, 'Bingo Long Traveling All-Stars & Motor Kings, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (432, 171, 1, 'Sucker Punch');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (433, 211, 40, 'Alexander the Great');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (434, 95, 22, 'Rafa');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (435, 297, 31, 'Ghost Dad');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (436, 281, 47, 'Rambo III');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (437, 120, 48, 'Three Seasons');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (438, 75, 39, 'Joneses, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (439, 124, 13, 'XX/XY');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (440, 191, 24, 'Brick Mansions');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (441, 156, 16, 'Toute la mémoire du monde');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (442, 82, 29, 'Day in the Country, A (Partie de campagne)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (443, 279, 45, 'Butchered');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (444, 132, 15, 'Black Watch, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (445, 179, 45, 'Clapham Junction');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (446, 234, 8, 'Dean Spanley');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (447, 185, 19, 'Boot, Das (Boat, The)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (448, 256, 27, 'Home from the Hill');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (449, 164, 2, 'Chamber, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (450, 229, 7, 'Immature, The (Immaturi)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (451, 220, 11, 'Love & Pop');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (452, 146, 18, 'Woman''s Face, A');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (453, 66, 40, 'Sunset Park');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (454, 274, 44, 'Taking Woodstock');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (455, 280, 47, 'Union Station');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (456, 106, 1, 'Action in the North Atlantic');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (457, 269, 35, 'Wolf');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (458, 22, 46, 'King''s Faith');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (459, 229, 21, 'Better Living Through Chemistry');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (460, 17, 29, 'Four Flies on Grey Velvet');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (461, 192, 49, 'Land of Plenty (Angst and Alienation in America)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (462, 24, 18, 'Little Witches');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (463, 101, 2, 'Moontide');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (464, 214, 18, 'Boy Wonder');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (465, 255, 12, 'Werner - Gekotzt wird später');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (466, 282, 46, 'Blood of the Vampire');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (467, 70, 20, 'Late Autumn (Man-choo)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (468, 133, 10, 'My Name is Khan');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (469, 247, 22, 'Legend of the Fist: The Return of Chen Zhen (Jing wu feng yun: Chen Zhen)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (470, 9, 38, 'Pure Luck');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (471, 47, 45, 'On the Road');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (472, 10, 45, 'Brown''s Requiem');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (473, 164, 14, 'Pill, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (474, 3, 40, 'Beautiful Creatures');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (475, 193, 43, 'Diary of a Wimpy Kid');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (476, 77, 16, 'Blankman');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (477, 247, 8, 'Afghan Star');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (478, 248, 6, 'Sounder');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (479, 236, 21, 'Teahouse of the August Moon, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (480, 215, 47, 'Not Reconciled (Nicht versöhnt oder Es hilft nur Gewalt wo Gewalt herrscht)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (481, 139, 43, 'Lion King 1½, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (482, 121, 43, 'Mostly Martha (Bella Martha)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (483, 187, 29, 'Garden Lovers (Eedenistä pohjoiseen)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (484, 24, 46, 'Summer at Grandpa''s, A (Dong dong de jia qi)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (485, 96, 47, 'Dracula');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (486, 219, 47, 'Bedtime Story');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (487, 73, 31, 'War of the Wildcats (In Old Oklahoma)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (488, 119, 14, 'Doomsday Prophecy');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (489, 230, 19, 'Once Upon a Time in China and America (Wong Fei Hung: Chi sai wik hung see) ');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (490, 213, 10, 'Brain Smasher... A Love Story (Bouncer and the Lady, The)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (491, 225, 43, 'Crazed Fruit (Kurutta kajitsu)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (492, 68, 9, 'Bonjour tristesse');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (493, 151, 6, 'Fun with Dick and Jane');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (494, 224, 9, 'Raisin in the Sun, A');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (495, 131, 33, 'Kwik Stop');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (496, 91, 40, 'Item, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (497, 265, 24, 'Sherlock Holmes Faces Death');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (498, 47, 6, 'Army of Crime (L''armée du crime)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (499, 129, 41, 'Cosmic Journey');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (500, 157, 23, 'Young Philadelphians, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (501, 23, 42, 'Skulls, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (502, 184, 19, 'Destroy All Monsters (Kaijû sôshingeki)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (503, 256, 48, 'Honeymooners, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (504, 124, 35, 'Funny Thing Happened on the Way to the Forum, A');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (505, 278, 32, 'Blue Light, The (Blaue Licht, Das)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (506, 293, 11, 'Woyzeck');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (507, 43, 15, 'North');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (508, 44, 27, 'Two for the Money');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (509, 48, 18, 'Emperor of the North (Emperor of the North Pole)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (510, 83, 13, 'Belly of an Architect, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (511, 11, 38, 'In the Line of Fire');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (512, 90, 20, 'Apple, The (Sib)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (513, 136, 40, 'Bitter Rice (Riso amaro)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (514, 147, 40, 'In the Mood For Love (Fa yeung nin wa)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (515, 156, 36, 'Dinosaurus!');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (516, 48, 12, 'Shadowing the Third Man');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (517, 299, 32, 'Heavyweights (Heavy Weights)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (518, 130, 32, 'Reef, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (519, 300, 13, 'War and Peace (Jang Aur Aman)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (520, 29, 7, 'Outpost: Black Sun');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (521, 87, 9, 'Adventure in Space and Time, An');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (522, 124, 42, 'Delphine 1, Yvan 0');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (523, 70, 33, 'The Legend of Bloody Jack');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (524, 12, 25, 'Voices');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (525, 48, 24, 'Malice N Wonderland');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (526, 147, 49, 'Nothing to Declare (Rien à déclarer)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (527, 144, 27, 'Winnie the Pooh');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (528, 213, 9, 'Camera Buff (Amator)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (529, 143, 23, 'Unknown Woman, The (Tuntematon emäntä)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (530, 187, 4, 'Cucaracha, La');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (531, 54, 3, 'City by the Sea');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (532, 268, 32, 'Lifeforce');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (533, 294, 50, 'Nine Lives (Ni liv)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (534, 296, 23, 'Edward Scissorhands');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (535, 227, 27, 'They Won''t Believe Me');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (536, 150, 41, 'Beck - Rum 302');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (537, 198, 9, 'Everybody''s Woman (La signora di tutti)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (538, 80, 20, 'Mr. Wonderful');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (539, 16, 42, 'Asterix & Obelix vs. Caesar (Astérix et Obélix contre César)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (540, 267, 29, 'I Confess');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (541, 7, 23, 'Heroine');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (542, 157, 14, 'Sirocco');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (543, 180, 42, 'Dragons Forever');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (544, 225, 1, 'Candyman 3: Day of the Dead');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (545, 74, 10, 'Spaghetti West, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (546, 32, 49, 'King Kelly');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (547, 154, 48, 'Niagara');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (548, 260, 50, 'American Sniper');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (549, 92, 30, 'Who''s Camus Anyway? (Kamyu nante shiranai)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (550, 124, 1, 'They');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (551, 123, 22, 'Fearless Freaks, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (552, 41, 18, 'Bright Lights');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (553, 120, 46, 'Ruling Class, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (554, 232, 1, 'Friday the 13th Part 2');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (555, 283, 44, 'Student, The (El estudiante)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (556, 38, 41, 'Pinky');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (557, 130, 30, 'Metrobranding');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (558, 15, 27, 'Symbiopsychotaxiplasm: Take One');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (559, 209, 19, 'Bomber');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (560, 240, 20, 'L!fe Happens');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (561, 242, 27, 'Bang Bang');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (562, 114, 12, 'Mantle');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (563, 212, 47, 'Terror, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (564, 160, 47, 'Abbott and Costello in Hollywood');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (565, 163, 50, 'Norwegian Wood (Noruwei no mori)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (566, 270, 6, '2:13');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (567, 287, 19, 'The Loyal 47 Ronin');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (568, 221, 32, 'Brothers Rico, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (569, 72, 31, 'My Favorite Brunette');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (570, 110, 44, 'First Sunday');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (571, 31, 15, 'Crucified Lovers, The (Chikamatsu monogatari)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (572, 67, 11, 'Little Fauss and Big Halsy');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (573, 134, 2, 'That''s Life!');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (574, 89, 22, 'My Future Boyfriend');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (575, 172, 28, 'Sun Don''t Shine');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (576, 46, 37, 'Dragon Hunters (Chasseurs de dragons)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (577, 204, 28, 'Lawn Dogs');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (578, 126, 17, 'Ultimate Gift, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (579, 168, 19, 'Brain Dead');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (580, 42, 33, 'I''m with Lucy');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (581, 127, 19, 'Yolki 2');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (582, 63, 20, 'Foster Brothers, The (Süt kardesler)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (583, 197, 50, 'See No Evil');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (584, 100, 34, 'Warrior and the Sorceress, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (585, 9, 34, 'Bikes vs Cars');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (586, 84, 23, 'Mutant Action (Acción Mutante)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (587, 5, 21, 'Enfer, L''');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (588, 187, 14, 'Target Shoots First, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (589, 102, 29, 'Shanghai Surprise');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (590, 108, 10, 'Tom Sawyer');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (591, 131, 18, 'Neighbouring Sounds (O som ao redor)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (592, 263, 8, 'Assassination of Jesse James by the Coward Robert Ford, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (593, 20, 29, 'Pocketful of Miracles');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (594, 110, 14, 'Guts (Agallas)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (595, 44, 49, 'Table No.21');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (596, 52, 8, 'The Bronze');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (597, 93, 6, 'Son in Law');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (598, 157, 15, 'Spring Break Shark Attack');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (599, 168, 29, 'Closed Curtain');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (600, 115, 30, 'Wildest Dream, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (601, 156, 1, 'Ebola Syndrome, The (Yi boh laai beng duk)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (602, 110, 13, 'White Rose, The (Weiße Rose, Die)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (603, 145, 41, 'Everybody Street');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (604, 135, 48, 'Girl Who Talked to Dolphins, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (605, 107, 13, 'Say It Isn''t So');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (606, 81, 40, 'Monster');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (607, 199, 15, 'Almost an Angel');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (608, 59, 21, 'White Elephant');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (609, 192, 5, 'One from the Heart');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (610, 266, 24, 'Pistol Whipped');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (611, 266, 29, 'River Called Titas, A (Titash Ekti Nadir Naam)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (612, 134, 32, 'Reef, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (613, 166, 27, 'Fog Over Frisco');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (614, 51, 4, 'My Afternoons with Margueritte (La tête en friche)');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (615, 35, 36, 'Rockin'' in the Rockies');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (616, 279, 27, 'Mummy''s Curse, The');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (617, 5, 32, 'My Best Girl');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (618, 168, 8, 'Alla älskar Alice');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (619, 99, 30, 'Orgazmo');
insert into trayectos (id_trayecto, id_estacion, id_tren, nombre) values (620, 21, 18, 'Valmont');
